### DISCUSSION TITLE
Custom nodes / edges

### DISCUSSION THREAD

**Discussion by maxi1555** [philippemerle/KubeDiagrams#18] [Ideas]
The tool is perfect to reflect the objects in the Kubernetes cluster, but it would be amazing if the tool also provide the possibility to add custom nodes and edges( extra layer to represent interactions, and promoting configurability :) ), some examples:
- Add nodes to represent external objects outside of the kubernetes cluster like "users" or "systems"
- Add edges to connect different objects derived and not derived from the manifest.yaml like service connections, a pod connecting to a service( classical example of a custom application using a DB or Caching ), or a pod connecting to an external application outside of the kubernetes cluster

**Comment by philippemerle** [comment]
@maxi1555 Amazing idea! This could allow one to document extra information not expressed in k8s resources! A feature to add for the KubeDiagrams 0.3.0 release. Do you agree that these extra nodes and edges should be declared in an extra config file?

**Reply by maxi1555** [reply]
It sounds perfect for me,that is the beauty of your tool, extensibility and customization :)

**Reply by philippemerle** [reply]
https://github.com/dmytrostriletskyi/diagrams-as-code/  allows one to declare nodes and edges in a yaml file. This could be a source of inspiration to take into account.

**Comment by philippemerle** [comment]
@maxi1555: I started to prototype your amazing idea. Following is a customized diagram for the wordpress example:
![test](https://github.com/user-attachments/assets/c3804e97-f468-4afc-b22c-4d0b466f1966)
The custom configuration file contains:
```yaml
diagram:
  nodes:
    users:
      name: Users
      type: diagrams.onprem.client.Users
  edges:
    - from: users
      to: wordpress/default/Service/v1
      xlabel: use
      fontcolor: gray
    - from: wordpress/default/Deployment/apps/v1
      to: wordpress-mysql/default/Service/v1
      color: brown
      fontcolor: red
      xlabel: calls
```
What do you thing about this?

**Reply by maxi1555** [reply]
It looks pretty nice, for the edges will be nice to be able to configure the line type and also if it is bidirectional. And as you already have the nodes and edges functionality in place why not adding also containers :) , use cases:
- Between the users and the namespace you have your infrastructure provider, and inside of it you could have a node representing a load balancer for example, that finally connects to the svc
- another example is to represent that your namespace is inside of a kubernetes cluster called xyz 
- having a representation of the kubernetes cluster you can automatically put the resources that does not belong to the namespaces like the pv, sc, node inside of it ( this maybe should be by default and not managed by the user... ), because as of today they are just floating outside if the namespace
- Other examples is to represent / group of nodes like applications running in a cloud or on premises 

In the end adding the container will help to group things outside of the namespaces giving to the consumers / users full flexibility

**Reply by philippemerle** [reply]
@maxi1555 style and direction of edges are already configurable. I will add support for custom clusters asap.

**Reply by maxi1555** [reply]
Hi @philippemerle , I've not doubt that you will make it possible.

Just final wish / other idea that will provide incalculable value related with customization, in the same way as you created the custom edges you could add an extra layer for "customization", in the sense that you as the provider have default coloring, line styles, backgrounds, but you will provide a way ( called customization file ) where us users can set dinamically the attributes in classes ( for reusability ) and finally assign them to specific objects ( basically CSS for the entire diagram :) ).

With this approach your tool will be perfect to draw the kubernetres objects, add whatever context around it ( custom nodes, edges and cluster ), and finally customize / influence any aspect of the generated diagram ( colors, lines types, background, etc - CSS ) , what do you think?. 

If you need me to raise a new idea with this no problem, also if you need someone to test it.

**Comment by philippemerle** [comment]
@maxi1555: Following diagram contains custom clusters:

![test](https://github.com/user-attachments/assets/775b7633-5c0e-4cbc-abcb-2dd774af526b)

Following is the associated custom configuration:

```yaml
diagram:
  clusters:
    aws:
      name: Amazon Web Service
      clusters:
        my-account:
          name: "Account: Philippe Merle"
          clusters:
            my-ekc:
              name: My Elastic Kubernetes Cluster
          nodes:
            foo:
              name: Philippe Merle
              type: diagrams.aws.general.User
      nodes:
        eck:
          name: Elastic Kubernetes Service
          type: diagrams.aws.compute.ElasticKubernetesService
  nodes:
    users:
      name: Users
      type: diagrams.onprem.client.Users
  edges:
    - from: users
      to: wordpress/default/Service/v1
      xlabel: use
      fontcolor: gray
    - from: wordpress/default/Deployment/apps/v1
      to: wordpress-mysql/default/Service/v1
      color: brown
      fontcolor: red
      xlabel: calls
  generate_diagram_in_cluster: aws.my-account.my-ekc
```

So, we could now define custom diagrams declaratively mixing both custom and generated clusters/nodes/edges!
This allows one to see the whole picture, don't it?
