### DISCUSSION TITLE
Is it possible to include port numbers under connection lines?

### DISCUSSION THREAD

**Discussion by thevops** [philippemerle/KubeDiagrams#9] [Q&A] [answered]
It'd be nice to have port numbers under connection lines between Service and Pods

**Comment by philippemerle** [comment]
Currently, edges are statically configured in YAML config files. For this case, this will require edges with a label set from resource data. I will investigate how to support this form of edges.

**Reply by thevops** [reply]
Thank you!

**Comment by philippemerle** [comment]
According to the following service manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-pod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-pod
```
Which fields (`name`, `port`, `protocol`, `targetPort`) do you want to display as label of the edge between the service and the workload pod? For instance the label of the edge could be `name:port->targetPort/protocol`, e.g., `http:80->8080/TCP`. Anything else?
